# Cloudflare Pages configuration
[env.production]
name = "nsbejr-website"
compatibility_date = "2024-01-01"

# Build settings
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Pages settings
[[pages]]
name = "nsbejr-website"
