name = "nsbejrsocal"
compatibility_date = "2024-01-01"

# Specify where your built files are located
pages_build_output_dir = "dist"

# Optional: Build configuration
[build]
command = "npm run build"
